version: '3'
services:
  vue:
    image: vuecli:1
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    container_name: mini-chat-client
    ports:
        - "9090:8080"
    volumes:
        - ./app:/app/
    stdin_open: true
networks:
  default:
    external:
      name: mini_chat
