version: '3'

services:
  user:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
        target: dev
      tty: true
      container_name: mini-chat-user
      restart: always
      volumes:
        - .:/go/src
      ports:
        - 8081:8080
  user_db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mini-chat-user-db
    restart: always
    volumes:
      - user_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root

networks:
  default:
    external:
      name: mini_chat

volumes:
  user_db: